JSarad_C868_Capstone/Models/Event.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace JSarad_C868_Capstone.Models
{
    public class Event
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        
        [Required, StringLength(100), DisplayName("Event Name")]
        public string EventName { get; set; }

        [Required,StringLength(50)]
        public string Type { get; set; }
        
        [Required, StringLength(200)]
        public string Location { get; set; }

        public DateTime EventDate { get; set; }
        
        public DateTime StartTime { get; set; }
        
        public DateTime EndTime { get; set; }

        [DisplayName("Includes Food")]
        public bool Food { get; set; }
        
        [DisplayName("Includes Bar")]
        public bool Bar { get; set; }

        [DisplayName("Number of Guests")]
        public int Guests { get; set; }
        public string? Notes { get; set; }

        [ForeignKey("Client")]
        public int ClientId { get; set; }
        
        public int? CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; } // changes when added

        public DateTime LastUpdate { get; set; } = DateTime.Now; //changes when updated
        //string 
        //string sql = "Insert into Capstone (EventName, EventType, StartDate, EndDate) Values ('{EventName}', '{EventType}', 
        
    }
}

JSarad_C868_Capstone/ViewModels/EventViewModel.cs
using JSarad_C868_Capstone.Data;
using JSarad_C868_Capstone.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace JSarad_C868_Capstone.ViewModels
{
    public class EventViewModel 
    {
        public string? Title { get; set; }
        public string? Notice { get; set; }
        public Event Event { get; set; }

        [Required]
        public string ClientName { get; set; }
        
    }
}
       

JSarad_C868_Capstone/Controllers/EventController.cs
using JSarad_C868_Capstone.Data;
using JSarad_C868_Capstone.Models;
using JSarad_C868_Capstone.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;


namespace JSarad_C868_Capstone.Controllers
{
    [Authorize]
    public class EventController : Controller
    {
        public SchedulingService _schedulingService = new SchedulingService();
        private readonly AppDbContext _db;
       
        //public Event selectedEvent { get; set; }
        public EventController(AppDbContext db)
        {
            _db = db;
           
        }

        // /Event
        //Returns Event List View Including Client name and Phone

        public IActionResult Index()
        {

            var events = from e in _db.Events
                         join c in _db.Clients on e.ClientId equals c.Id
                         select new EventListDetails
                         {
                             EventId = e.Id,
                             EventName = e.EventName,
                             EventDate = e.EventDate,
                             StartTime = e.StartTime,
                             EndTime = e.EndTime,
                             Type = e.Type,
                             ClientId = e.ClientId,
                             ContactName = c.Name,
                             Phone = c.Phone
                         };


            events = events.OrderBy(e => e.StartTime);

            return View(events.ToList());

        }

        //Event list view with table search option (returns Events by type)
        [HttpPost]
        public async Task<IActionResult> Index(string? search)
        {
            ViewData["GetEvent"] = search;
            var searchQuery = from e in _db.Events
                              join c in _db.Clients on e.ClientId equals c.Id
                              select new EventListDetails
                              {
                                  EventId = e.Id,
                                  EventName = e.EventName,
                                  EventDate = e.EventDate,
                                  StartTime = e.StartTime,
                                  EndTime = e.EndTime,
                                  Type = e.Type,
                                  ClientId = e.ClientId,
                                  ContactName = c.Name,
                                  Phone = c.Phone
                              };

            if (!string.IsNullOrEmpty(search))
            {
                searchQuery = searchQuery.Where(e => e.Type.Contains(search)).OrderBy(s => s.StartTime);
            }
            else
            {
                searchQuery = searchQuery.OrderBy(s => s.StartTime);
                return View("Index", searchQuery);
            }
            return View(await searchQuery.AsNoTracking().ToListAsync());
        }

        //Get: /Event/Modify/{id}

        [HttpGet]
        public IActionResult Modify(int id)
        {
            EventViewModel viewModel = new EventViewModel();
                      
            if (id == 0)
            {
                viewModel.Event = new Event();
                viewModel.Event.EventDate = DateTime.Parse(DateTime.Now.ToString("MM/dd/yyyy hh:mm tt"));
                viewModel.Event.StartTime = DateTime.Parse(DateTime.Now.ToString("MM/dd/yyyy hh:mm tt"));
                viewModel.Event.EndTime = DateTime.Parse(DateTime.Now.ToString("MM/dd/yyyy hh:mm tt"));
                viewModel.Event.CreatedOn = DateTime.Parse(DateTime.Now.ToString("MM/dd/yyyy hh:mm tt"));
                viewModel.Title = "Add Event";
                viewModel.Event.Notes = "...";
                
            }
        
            else
            {
                viewModel.Event = _db.Events.Find(id);
                var client = _db.Clients.Find(viewModel.Event.ClientId);
                viewModel.ClientName = client.Name;
                viewModel.Title = "Edit Event";
                viewModel.Notice = "Notice: making changes to event dates will remove any associated employee schedules for this event. " +
                    "Making changes to event times may cause incorrect employee schedule times. Please double check employee schedule times after making" +
                    " changes to the event times.";
            }
            
            return PartialView("_ModifyEventModalPartial", viewModel); ;
        }

        //Post: /Event/Modify/{id}
        /*adds and edits and event. Code behind for ~Views/Event/_ModifyEventModalPartial.
          Called from site.js Modify Object Function*/
        [HttpPost]
        public IActionResult Modify(EventViewModel viewModel)
        {
            bool isStartBeforeEnd = false;
            bool isClient = false;
            bool isBusinessHours = false;
            //var clients = _db.Clients;
            int eventId = viewModel.Event.Id;
            var eventSchedule = from es in _db.EventSchedules where es.EventId == eventId select es;

            viewModel.Event.StartTime = viewModel.Event.EventDate.Date + viewModel.Event.StartTime.TimeOfDay;
            viewModel.Event.EndTime = viewModel.Event.EventDate.Date + viewModel.Event.EndTime.TimeOfDay;
            viewModel.Event.CreatedBy = Constants.currentUser.Id;
            viewModel.Event.CreatedOn = DateTime.Now;
            
            if (string.IsNullOrEmpty(viewModel.Event.Notes))
            {
                viewModel.Event.Notes = "...";
            }

            // validate start time is scheduled before end time
            isStartBeforeEnd = _schedulingService.IsStartBeforeEnd(viewModel.Event.StartTime, viewModel.Event.EndTime);
            if (!isStartBeforeEnd)
            {
                ModelState.AddModelError("Event.EndTime", "* Event start time must be before Event end time");
            }

            //validate start and end time are during business hours
            isBusinessHours = _schedulingService.IsDuringBusinessHours(viewModel.Event.StartTime, viewModel.Event.EndTime);
            if(!isBusinessHours)
            {
                ModelState.AddModelError("Event.EndTime", "* Events must be scheduled during hours of operation between 6:00 am and 11:00 pm");
            }

            if (viewModel.Event.Guests < 0)
            {
                ModelState.AddModelError("Event.Guests", "The number of guests cannot be negative");
            }

            if (viewModel.ClientName != null)
            {
                var clients = _db.Clients;
                if (clients.Any())
                {
                    foreach (var client in clients)
                    {
                        if (client.Name.ToUpper() == viewModel.ClientName.ToUpper())
                        {
                            viewModel.Event.ClientId = client.Id;
                            isClient = true;
                            break;
                        }
                    }
                }
            }

            if(!isClient)
            {
                ModelState.AddModelError("ClientName", "No client by this name exists");
            }

            if (ModelState.IsValid)
            {
                //viewModel.Event.ClientId = viewModel.Client.Id;
                if (eventId == 0)
                {
                    _db.Events.Add(viewModel.Event);
                }
                else
                {

                    if (eventSchedule.Any())
                    {
                        IsScheduleConflictRemoved(eventId, viewModel.Event.StartTime);
                    }
                    _db.Events.Update(viewModel.Event);
                    
                }
                _db.SaveChanges();
                return Ok(true);
                //reload from js does not resort my dates in list

            }
            return PartialView("_ModifyEventModalPartial", viewModel);
        }

        [HttpPost]
        public IActionResult DeletePOST(int? id)
        {
            //if (id == null || id == 0)
            //{
                var selectedEvent = _db.Events.Find(id);
                if (selectedEvent == null)
                {
                    return NotFound();
                }
                
                var eventSchedules = from e in _db.EventSchedules where e.EventId == id select e;
                if (eventSchedules.Any())
                {
                    foreach (EventSchedule eventSchedule in eventSchedules)
                    {
                        var schedule = _db.Schedules.Where(s => s.Id == eventSchedule.ScheduleId).FirstOrDefault();
                        _db.Schedules.Remove(schedule);
                        _db.EventSchedules.Remove(eventSchedule);
                    }
                }
                _db.Events.Remove(selectedEvent);
                _db.SaveChanges();
            //}
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult AddSchedule(int id)
        {
            EventScheduleViewModel viewModel = new EventScheduleViewModel();


            viewModel.Event = _db.Events.Find(id);
            viewModel.Client = _db.Clients.Find(viewModel.Event.ClientId);
            viewModel.EmployeeSchedule = new ScheduleDisplayDetails();

            viewModel.EmployeeSchedule.StartTime = viewModel.Event.StartTime;
            viewModel.EmployeeSchedule.EndTime = viewModel.Event.EndTime;
            viewModel.EmployeeList = _db.Employees.ToList();
            viewModel.Includes = Included(viewModel.Event);

            viewModel.Schedules = (from es in _db.EventSchedules
                                   join s in _db.Schedules on es.ScheduleId equals s.Id
                                   join e in _db.Employees on s.EmployeeId equals e.Id
                                   where es.EventId == viewModel.Event.Id

JSarad_C868_Capstone/Views/Event/AddSchedule.cshtml
@model JSarad_C868_Capstone.ViewModels.EventScheduleViewModel


<div class="container p3" style="height:83vh">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Event Details & Scheduling</h2>
        </div>
        <div class="col-6 text-end" style="margin-top:20px">
                <!--button to return to Events page -->
            <a class="btn btn-primary text-end" asp-controller="Event" asp-action="Index" style="width:150px">Return to Events</a>
        </div>
    </div>
    <br />
    <div id="PlaceHolderHere"></div>
    <form method="post">
        <div class="row">
            <div class="col md-4" style="padding-top:1.7%;">
               @* <div class="p-2" style="height:68vh; box-shadow: 0px 0px 3px rgba(0,0,0,0.9); border: 1px solid black; position: relative; min-height:600px;">*@
                <div class="details-wrapper">
                    <div class="details-container">
                       <h4 style="margin-top:10px;"><b>@Html.Raw(Model.Event.EventName)</b> </h4>
                        <hr />
                        <div style="margin-left:10px; margin-right:10px">
                            <input asp-for="Event.Id" type="hidden" class="eventId" id="eventId"/>
                            <input asp-for="Client.Id" type="hidden" class="clientId" />
                            <p><b> Event Date: </b> @($"{Model.Event.StartTime.ToLongDateString()}")</p>
                            <p><b> Event Time: </b> @($"{Model.Event.StartTime.ToShortTimeString()}") - @($"{Model.Event.EndTime.ToShortTimeString()}")</p>
                            @*<p><b> End Time: </b> </p>*@
                            <p><b> Type: </b> @($"{Model.Event.Type}")</p>
                            <p><b> Location: </b> @($"{Model.Event.Location}")</p>
                            <p><b> Number of Guests: </b> @($" {Model.Event.Guests}")</p>
                            <p><b> Event Includes: </b> @($"{Model.Includes}")</p>
                            @* <h4><b> Contact Information: </b></h4>*@
                            <p> <b> Contact: </b> @($"{Model.Client.Name}")</p>
                            <p> <b> Phone: </b>@($"{Model.Client.Phone}")</p>
                            <p> <b> Email Address: </b>@($"{Model.Client.Email}")</p>
                            <p> <b>Notes: </b></p>
                            <div class="note-wrapper" style="padding:10px">
                                <p> @($"{Model.Event.Notes}")</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                     
                          
            <div class="col-md-8 pt-4">
                <div class="small-outer-wrapper">
                    <div class="small-tc">
                        <div class="small-table-wrapper">
                            <!--table row headers-->
                            <table class="table table-bordered border-dark table-primary table-hover table-sm">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>Position</th>
                                        <th>Availability</th>
                                        <th>Phone</th>
                                    </tr>
                                </thead>
                                
                                <!--table body and population info-->
                                <tbody>
                                    @if (Model.EmployeeList != null && Model.EmployeeList.Any())
                                    {
                                        foreach (var employee in Model.EmployeeList)
                                        {
                                            int index = Model.EmployeeList.IndexOf(employee);
                                            <tr asp-for="SelectedEmployee" class="table-light selectable"
                                                controller="Event" action="EmployeeSelection" data-id="@employee.Id" data-index="@index">

                                                <td>@employee.Id</td>
                                                <input type="hidden" asp-for="EmployeeList[index].Id" />
                                                <td>@employee.Name</td>
                                                <input type="hidden" asp-for="EmployeeList[index].Name" />
                                                <td>@employee.Role</td>
                                                <input type="hidden" asp-for="EmployeeList[index].Role" />
                                                <td>@employee.Availability</td>
                                                <input type="hidden" asp-for="EmployeeList[index].Availability" />
                                                <td>@employee.Phone</td>
                                                <input type="hidden" asp-for="EmployeeList[index].Phone" />
                                           
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                    
                             
                            
                <div class="row mt-3">
                    <input asp-for="EmployeeSchedule.EmployeeId" id="selectedId" type="hidden" />
                   
                    <div class="col-3 form-group">
                        <label>Employee Name</label>
                        <input asp-for="EmployeeSchedule.EmployeeName" class="selectionResult" style="display:flex" readonly /> 
                        
                        </div>
                    <div class="col-2 form-group">
                        <div class="input-append">
                        <label asp-for="EmployeeSchedule.StartTime" style="display:flex">Start Time</label>
                            <input asp-for="EmployeeSchedule.StartTime" type="time" /> 
                            
                            <span class="add-on">
                            <i data-time-icon="icon-time"></i>
                            </span> 
                        </div>
                    </div>
                    <div class="col-2 form-group">
                        <div class="input-append">
                            <label asp-for="EmployeeSchedule.EndTime" style="display:flex">End Time</label>
                            <input asp-for="EmployeeSchedule.EndTime" type="time" /> 
                          
                            <span class="add-on">
                                <i data-time-icon="icon-time"></i>
                            </span>
                        </div>
                    </div>
                    
                    <div class="col-5 form-group pt-3 text-end">
                        <button class="btn btn-primary" type="submit" formaction="AddSchedule" id="readyDocument" style="width:150px">Add To Schedule

                        </button> 
                    </div>
                </div>
                
                <div class="pt-2">
                <div class="small-outer-wrapper">
                    <div class="small-tc">
                        <div class="small-table-wrapper">
                           
                            <table class="table table-bordered border-dark table-primary table-hover table-sm">
                           
                                <thead>
                                    <tr >
                                                
                                    <th>Schedule Id</th>
                                        <th>Employee Id</th>
                                        <th>Employee Name</th>
                                        <th>Start Time</th>
                                        <th>End Time</th>
                                        <th style="z-index:2;">Remove </th>
                                                
                                    </tr>
                                </thead>
                                <!--table body and population info-->
                                <tbody >
                                    
                                    @if (Model.Schedules != null)
                                    {
                                        foreach (var schedule in Model.Schedules)
                                        {
                                            int index = Model.Schedules.IndexOf(schedule);
                                            <tr id="row_@schedule.ScheduleId" class="table-light"
                                    controller="Event" action="Selection" data-id="@schedule.EmployeeId">
                                           
                                            <td>@schedule.ScheduleId</td>
                                                <input type="hidden" asp-for="Schedules[index].ScheduleId" />
                                                <td >@schedule.EmployeeId</td>
                                                <input type="hidden" asp-for="Schedules[index].EmployeeId" />
                                                <td >@schedule.EmployeeName</td>
                                                <input type="hidden" asp-for="Schedules[index].EmployeeName" />
                                                <td asp-format="time">@schedule.StartTime.ToShortTimeString()</td>
                                                <input type="hidden" asp-for="Schedules[index].StartTime"  />
                                                <td  asp-format="time">@schedule.EndTime.ToShortTimeString()</td>
                                                <input type="hidden" asp-for="Schedules[index].EndTime"  />
                                                <td class="w-100 btn-group" role="group" style="z-index:1;">
                                                   
                                                <a class="btn btn-danger btn-sm delete-unselectable" id="#deleteUnselectable" data-controller="Event" data-action="RemoveSchedule" data-id="@schedule.ScheduleId"
                                                    data-index="@index" data-body-message="Are you sure you want to remove this schedule?" >
                                                    <i class="bi bi-trash"></i> Remove
                                                </a>
                                                </td>
                                               
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                </div>
                <div class="row pt-4">
                    <div class="col-9">
                        <p >
                            <small>
                            California State Law requires employees recieve overtime at a rate of time and a half for any hours in excess
                            of 40 per week or 8 per day, and a rate of double time for any hours in excess of 12 per day.
                            </small>
                        </p>
                    </div>
                    <div class="col-3 text-end" style="margin-top:1vh;">
                        <button class="btn btn-danger text-end" formaction="/Event/CheckOT" style="width:150px">Check Overtime</button> @*formaction="/AddSchedule"*@
                       
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@section Scripts {
    <script type="text/javascript">
        function openErrorModal(strMessage) {
            var errorDiv = document.getElementById("errorModalBody");
            errorDiv.innerHTML = (strMessage);
            $('#errorModal').modal('show');
        }

        
        $(document).ready(function () {
            
            var msg = "@TempData["Error"]";
            if (msg)
                openErrorModal(msg);
           
        });
        
       
    </script>
 }
 

JSarad_C868_Capstone/Views/Event/Index.cshtml
@model IEnumerable<EventListDetails>

<!--placeholder for _ModifyEventModalPartial (Modify Object function in site.js-->
<div id="PlaceHolderHere"></div>


<div class="container p3" style="height:83vh">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Event Information</h2>
        </div>
        <div class="col-6 text-end" style="margin-top:20px">
            <!--button to _ModifyEventModalPartial "Add" (js.ModifyObject)-->
            <button type="button" class="btn btn-primary" data-bs-toggle="ajax-modal" data-target="#modifyEvent"
                    data-controller="Event" data-action="Modify" data-modify-type="Add">
                    Add Event
            </button>
        </div>
    </div>
    <br />

    <!--search bar and button (/Event/Index/string)-->
    <form method="post" asp-action="Index">
        <p>
            <input type="search" placeholder="Search Event By Type" value="@ViewData["GetEvent"]" name="search" style="width:500px;" />
            <input type="submit" value="Search" class="btn btn-primary" />
            <a asp-action="Index">Get All Events</a>
        </p>
    </form>
    
    <!--table body and population info for Event (/Event/Index)-->
    <div class="outer-wrapper">
        <div class="tc">
            <div class="table-wrapper">
                <table class="table table-bordered border-dark table-primary table-hover" style="width:100%">
                    <thead>
                        <tr>
                            <th>Event Date</th>
                            <th>Start Time</th>
                            <th>End Time</th>
                           @* <th>Event Id</th>*@
                            <th>Event Name</th>
                            <th>Event Type</th>
                            <th>Contact Name</th>
                            <th>Contact Phone</th>
                           
                        </tr>
                    </thead>
                    
                    <tbody>
                       
                        @*track index of IEnumerable*@
                        @{int index = -1;
                            @foreach (var item in Model)
                            { 
                                index++;
                                <tr id="row_@item.EventId" class="table-light selectable" controller="Event" Action="Selection" 
                                    data-id="@item.EventId" data-index="@index">
                                    @*<td>@item.EventId</td>*@
                                    <td>@item.EventDate.ToShortDateString()</td>
                                    <td>@item.StartTime.ToShortTimeString()</td>
                                    <td>@item.EndTime.ToShortTimeString()</td>
                                    <td>@item.EventName</td>
                                    <td>@item.Type </td>
                                   
                                    <td>@item.ContactName</td>
                                    <td>@item.Phone</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
        @*hidden input field for selected employee (js call back)*@
        <input id="selectedId" class="form-control" type="hidden"/>
        <div class="buttons">

            <!--button call to Add Event employee Schedule (Open Add Schedule function site.js ->/Event/AddSchedule/{id})-->
            <a class="btn btn-secondary" id="details"
               data-controller="Event" data-action="AddSchedule">
                <i class="bi bi-trash"></i> Details & Scheduling
            </a> @*data-controller="Event" data-action="AddSchedule"*@
            
            <!--button call to modify modal "Edit" (Modify Object function site.js) -->
            <button class="btn btn-primary" data-bs-toggle="ajax-modal" data-target="#modifyEvent"
                    data-controller="Event" data-action="Modify" data-modify-type="Edit">
                    Edit
            </button>
                 
            <!--button call to delete modal (js.delete.js)-->
            <a class="btn btn-danger delete" id="#delete"
                data-controller="Event" data-Action="DeletePOST"
               data-body-message="Removing an event will remove any associated
                                      employee schedules for the event. Are you sure you want to delete this event?">
                <i class="bi bi-trash"></i> Delete
            </a>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $(".active").removeClass("active");
            $("#link-event").addClass("active");
        });
    </script>
 }
                