JSarad_C868_Capstone/Controllers/EventController.cs
using JSarad_C868_Capstone.Data;
using JSarad_C868_Capstone.Models;
using JSarad_C868_Capstone.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;


namespace JSarad_C868_Capstone.Controllers
{
    [Authorize]
    public class EventController : Controller
    {
        public SchedulingService _schedulingService = new SchedulingService();
        private readonly AppDbContext _db;
       
        //public Event selectedEvent { get; set; }
        public EventController(AppDbContext db)
        {
            _db = db;
           
        }

        // /Event
        //Returns Event List View Including Client name and Phone

        public IActionResult Index()
        {

            var events = from e in _db.Events
                         join c in _db.Clients on e.ClientId equals c.Id
                         select new EventListDetails
                         {
                             EventId = e.Id,
                             EventName = e.EventName,
                             EventDate = e.EventDate,
                             StartTime = e.StartTime,
                             EndTime = e.EndTime,
                             Type = e.Type,
                             ClientId = e.ClientId,
                             ContactName = c.Name,
                             Phone = c.Phone
                         };


            events = events.OrderBy(e => e.StartTime);

            return View(events.ToList());

        }

        //Event list view with table search option (returns Events by type)
        [HttpPost]
        public async Task<IActionResult> Index(string? search)
        {
            ViewData["GetEvent"] = search;
            var searchQuery = from e in _db.Events
                              join c in _db.Clients on e.ClientId equals c.Id
                              select new EventListDetails
                              {
                                  EventId = e.Id,
                                  EventName = e.EventName,
                                  EventDate = e.EventDate,
                                  StartTime = e.StartTime,
                                  EndTime = e.EndTime,
                                  Type = e.Type,
                                  ClientId = e.ClientId,
                                  ContactName = c.Name,
                                  Phone = c.Phone
                              };

            if (!string.IsNullOrEmpty(search))
            {
                searchQuery = searchQuery.Where(e => e.Type.Contains(search)).OrderBy(s => s.StartTime);
            }
            else
            {
                searchQuery = searchQuery.OrderBy(s => s.StartTime);
                return View("Index", searchQuery);
            }
            return View(await searchQuery.AsNoTracking().ToListAsync());
        }

        //Get: /Event/Modify/{id}

        [HttpGet]
        public IActionResult Modify(int id)
        {
            EventViewModel viewModel = new EventViewModel();
                      
            if (id == 0)
            {
                viewModel.Event = new Event();
                viewModel.Event.EventDate = DateTime.Parse(DateTime.Now.ToString("MM/dd/yyyy hh:mm tt"));
                viewModel.Event.StartTime = DateTime.Parse(DateTime.Now.ToString("MM/dd/yyyy hh:mm tt"));
                viewModel.Event.EndTime = DateTime.Parse(DateTime.Now.ToString("MM/dd/yyyy hh:mm tt"));
                viewModel.Event.CreatedOn = DateTime.Parse(DateTime.Now.ToString("MM/dd/yyyy hh:mm tt"));
                viewModel.Title = "Add Event";
                viewModel.Event.Notes = "...";
                
            }
        
            else
            {
                viewModel.Event = _db.Events.Find(id);
                var client = _db.Clients.Find(viewModel.Event.ClientId);
                viewModel.ClientName = client.Name;
                viewModel.Title = "Edit Event";
                viewModel.Notice = "Notice: making changes to event dates will remove any associated employee schedules for this event. " +
                    "Making changes to event times may cause incorrect employee schedule times. Please double check employee schedule times after making" +
                    " changes to the event times.";
            }
            
            return PartialView("_ModifyEventModalPartial", viewModel); ;
        }

        //Post: /Event/Modify/{id}
        /*adds and edits and event. Code behind for ~Views/Event/_ModifyEventModalPartial.
          Called from site.js Modify Object Function*/
        [HttpPost]
        public IActionResult Modify(EventViewModel viewModel)
        {
            bool isStartBeforeEnd = false;
            bool isClient = false;
            bool isBusinessHours = false;
            //var clients = _db.Clients;
            int eventId = viewModel.Event.Id;
            var eventSchedule = from es in _db.EventSchedules where es.EventId == eventId select es;

            viewModel.Event.StartTime = viewModel.Event.EventDate.Date + viewModel.Event.StartTime.TimeOfDay;
            viewModel.Event.EndTime = viewModel.Event.EventDate.Date + viewModel.Event.EndTime.TimeOfDay;
            viewModel.Event.CreatedBy = Constants.currentUser.Id;
            viewModel.Event.CreatedOn = DateTime.Now;
            
            if (string.IsNullOrEmpty(viewModel.Event.Notes))
            {
                viewModel.Event.Notes = "...";
            }

            // validate start time is scheduled before end time
            isStartBeforeEnd = _schedulingService.IsStartBeforeEnd(viewModel.Event.StartTime, viewModel.Event.EndTime);
            if (!isStartBeforeEnd)
            {
                ModelState.AddModelError("Event.EndTime", "* Event start time must be before Event end time");
            }

            //validate start and end time are during business hours
            isBusinessHours = _schedulingService.IsDuringBusinessHours(viewModel.Event.StartTime, viewModel.Event.EndTime);
            if(!isBusinessHours)
            {
                ModelState.AddModelError("Event.EndTime", "* Events must be scheduled during hours of operation between 6:00 am and 11:00 pm");
            }

            if (viewModel.Event.Guests < 0)
            {
                ModelState.AddModelError("Event.Guests", "The number of guests cannot be negative");
            }

            if (viewModel.ClientName != null)
            {
                var clients = _db.Clients;
                if (clients.Any())
                {
                    foreach (var client in clients)
                    {
                        if (client.Name.ToUpper() == viewModel.ClientName.ToUpper())
                        {
                            viewModel.Event.ClientId = client.Id;
                            isClient = true;
                            break;
                        }
                    }
                }
            }

            if(!isClient)
            {
                ModelState.AddModelError("ClientName", "No client by this name exists");
            }

            if (ModelState.IsValid)
            {
                //viewModel.Event.ClientId = viewModel.Client.Id;
                if (eventId == 0)
                {
                    _db.Events.Add(viewModel.Event);
                }
                else
                {

                    if (eventSchedule.Any())
                    {
                        IsScheduleConflictRemoved(eventId, viewModel.Event.StartTime);
                    }
                    _db.Events.Update(viewModel.Event);
                    
                }
                _db.SaveChanges();
                return Ok(true);
                //reload from js does not resort my dates in list

            }
            return PartialView("_ModifyEventModalPartial", viewModel);
        }

        [HttpPost]
        public IActionResult DeletePOST(int? id)
        {
            //if (id == null || id == 0)
            //{
                var selectedEvent = _db.Events.Find(id);
                if (selectedEvent == null)
                {
                    return NotFound();
                }
                
                var eventSchedules = from e in _db.EventSchedules where e.EventId == id select e;
                if (eventSchedules.Any())
                {
                    foreach (EventSchedule eventSchedule in eventSchedules)
                    {
                        var schedule = _db.Schedules.Where(s => s.Id == eventSchedule.ScheduleId).FirstOrDefault();
                        _db.Schedules.Remove(schedule);
                        _db.EventSchedules.Remove(eventSchedule);
                    }
                }
                _db.Events.Remove(selectedEvent);
                _db.SaveChanges();
            //}
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult AddSchedule(int id)
        {
            EventScheduleViewModel viewModel = new EventScheduleViewModel();


            viewModel.Event = _db.Events.Find(id);
            viewModel.Client = _db.Clients.Find(viewModel.Event.ClientId);
            viewModel.EmployeeSchedule = new ScheduleDisplayDetails();

            viewModel.EmployeeSchedule.StartTime = viewModel.Event.StartTime;
            viewModel.EmployeeSchedule.EndTime = viewModel.Event.EndTime;
            viewModel.EmployeeList = _db.Employees.ToList();
            viewModel.Includes = Included(viewModel.Event);

            viewModel.Schedules = (from es in _db.EventSchedules
                                   join s in _db.Schedules on es.ScheduleId equals s.Id
                                   join e in _db.Employees on s.EmployeeId equals e.Id
                                   where es.EventId == viewModel.Event.Id

JSarad_C868_Capstone/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using JSarad_C868_Capstone.Models;
using JSarad_C868_Capstone.Data;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;

namespace JSarad_C868_Capstone.Controllers
{
    public class LoginController : Controller
    {

        //public static User CurrentUser { get; set; }
        public Constants dataService;
        private readonly AppDbContext _db;

        public LoginController(AppDbContext db)
        {
            _db = db;
        }
        [HttpGet]
        public IActionResult Index()
        {
            User administrator = new User();
            return View(administrator);

        }

        [HttpPost]
        public async Task<IActionResult> SignIn(User? administrator)
        {
            int adminId;
            var admin = _db.Users.ToList();
           
            if (!ModelState.IsValid) 
            {
                return View("Index", administrator);
            }
            //else if (User) { }
            
            foreach(User user in admin)
            {
                if (user.Username == administrator.Username && user.Password == administrator.Password)
                {
                    adminId = user.Id;
                    Constants.currentUser = _db.Users.Find(adminId);

                    var claims = new List<Claim> 
                    { 
                        new Claim(ClaimTypes.Name, user.Username),
                        new Claim(ClaimTypes.Email, "admin@catering.com")
                    };
                    var identity = new ClaimsIdentity(claims, "CookieAuth");
                    ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync("CookieAuth", claimsPrincipal);
                    return RedirectToAction("Index", "Event");

                }
            }

            ModelState.AddModelError("Password", "Invalid Username or Password");
            return View("Index", administrator);
        }

        [HttpPost] 
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync("CookieAuth");
            return RedirectToAction("Index");
        }
    }
}

JSarad_C868_Capstone/Controllers/ReportsController.cs
using JSarad_C868_Capstone.Data;
using JSarad_C868_Capstone.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JSarad_C868_Capstone.Models;

namespace JSarad_C868_Capstone.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private readonly AppDbContext _db;

        public ReportsController(AppDbContext db)
        {
            _db = db;
        }

        
        public IActionResult Index()
        {
            
            ReportsViewModel viewModel = new ReportsViewModel();
            viewModel.UserSelectList = BindSelectList();
            viewModel.StartDate = DateTime.Now;
            viewModel.EndDate = DateTime.Now;
            viewModel.EventList = _db.Events.OrderBy(e => e.StartTime).ToList();
            
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Index(ReportsViewModel viewModel)
        {
            ModelState.Clear();
            viewModel.UserSelectList = BindSelectList();
            int userId = Convert.ToInt32(viewModel.SelectedUser);
           
            //determine which filter result to return based on user input
            if (viewModel.OrderByPlanner)
            {
                if (userId > 0)
                {
                    if (viewModel.OrderByDates == true)
                    {
                        viewModel.EventList = (from e in _db.Events
                                               where e.CreatedBy == userId
                                               && e.StartTime.Date >= viewModel.StartDate.Date
                                               && e.EndTime.Date <= viewModel.EndDate.Date
                                               orderby e.StartTime
                                               select e).ToList();
                        return View(viewModel);
                    }
                    viewModel.EventList = _db.Events.Where(e => e.CreatedBy == userId).OrderBy(e => e.StartTime).ToList();
                    return View(viewModel);
                }
                viewModel.EventList = _db.Events.OrderBy(e => e.StartTime).ToList();
                TempData["Error"] = "Please select a planner";
                return View(viewModel);
            }

            if (viewModel.OrderByDates)
            {
                viewModel.EventList = (from e in _db.Events
                                       where e.StartTime.Date >= viewModel.StartDate.Date
                                       && e.EndTime.Date <= viewModel.EndDate.Date
                                       orderby e.StartTime
                                       select e).ToList();
                return View(viewModel);
            }
            viewModel.EventList = _db.Events.OrderBy(e => e.StartTime).ToList();
            TempData["Error"] = "Please select how you would like to filter your results from the provided checkboxes";
            return View(viewModel);
        }

        public List<SelectListItem> BindSelectList()
        {
            var usersData = _db.Users;
            List<SelectListItem> UserSelectList = new List<SelectListItem>();
            UserSelectList.Insert(0, new SelectListItem
            {
                Text = "--select planner--",
                Value = "0"
            });

            foreach (User user in usersData)
            {
                UserSelectList.Add(new SelectListItem
                {
                    Text = user.Username,
                    Value = user.Id.ToString()
                });
            }
            return UserSelectList;
        }
    }
}

JSarad_C868_Capstone/Views/Shared/_DeleteConfirmationModal.cshtml
@*@model Employee

<div class="modal fade" id="confirmDelete" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="deleteModalLabel">
    <div class="modal-dialog">
        <div class="modal-content"> 
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Delete Employee</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
                <input asp-for="Id" type="hidden" />
                    <p>Are you sure you would like to delete this employee</p>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a asp-controller="Employee" asp-action="DeletePOST" asp-route-id="Id"
                class="btn btn-danger mx-2"> Delete</a>
            </div>
        </div>
    </div>
</div>*@

JSarad_C868_Capstone/Views/Shared/_ErrorModalPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@*<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Warning</h4>
            </div>
            <div class="modal-body delete-modal-body">
                <h1 value="@ViewData["Error"]"></h1>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-bs-dismiss="modal" id="confirm">Ok</button>
                @*<button type="submit" class="btn btn-danger" id="confirm-delete">Delete</button>
            </div>
        </div>
    </div>
</div>*@

JSarad_C868_Capstone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - JSarad_C868_Capstone</title>
    
        <!--bootstrap.css-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <!--Flatly Theme-->
        <link rel="stylesheet" href="~/css/BootswatchFlatlyTheme.css" />
    
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/JSarad_C868_Capstone.styles.css" asp-append-version="true" />
        <link href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css"
    
        rel="stylesheet" type="text/css" />
   
    </head>
    <body style="background-color:#f9f9f9">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                <div class="container-fluid">
                <a class="navbar-brand" style="color:#63b8a7; font-size:25px" href="#">Capstone Catering</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarColor01">
                       
                        <ul class="navbar-nav me-auto">
                       
                            <li class="nav-item inactive">
                                <a class="nav-link" id="link-event" asp-area="" asp-controller="Event" asp-action="Index">Events</a>
                            </li>
                            <li class="nav-item inactive">
                            <a class="nav-link" id="link-client" asp-area="" asp-controller="Client" asp-action="Index">Clients</a>
                            </li>
                            <li class="nav-item inactive">
                                <a id="link-employee" class="nav-link" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                            </li>
                            <li class="nav-item inactive">
                                <a id="link-reports" class="nav-link" asp-area="" asp-controller="Reports" asp-action="Index">Reports</a>
                            </li>
                       
                        </ul>
                    
                        
                    
                        <div class="text-end">
                            <partial name="_LoginStatusPartial" />
                        </div>
                    </div>
                </div>
            </nav>
       
        </header>
        <div class="container">
            <main role="main" class="pb-3">

                <!--Error Dialog-->
                <div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title" id="myModalLabel">Warning</h4>
                            </div>
                            <div class="modal-body" id="errorModalBody" style="white-space:pre-wrap"> </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="confirm">Ok</button>
                            </div>
                        </div>
                    </div>
                </div>

                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - JSarad_C868_Capstone - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/delete.js" asp-append-version="true"></script>
    
    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.0.min.js" type="text/javascript"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
  
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>


@* <link href="~/lib/jquery-ui-1.13.2.custom/jquery-ui.min.css" rel="stylesheet" />*@
@* <script src="~/lib/jquery-ui-1.13.2.custom/jquery-ui.min.js"></script>*@

JSarad_C868_Capstone/Views/Shared/_LoginStatusPartial.cshtml
@if (User.Identity.IsAuthenticated)
{
    <form method="post" asp-controller="Login" asp-action="Logout">
        
        <p style="color:lightgray; display:inline-flex;">Welcome @User.Identity.Name</p>

        <button type="submit" class="m-2 btn btn-link">Logout</button>
    </form>
}
else
{
    <a class="btn btn-link" asp-route="/Login/Index"></a>
}